version: '3.2'

services:
  httpd:
    image: httpd:2.4
    ports:
      - 80:80
      - 443:443
    networks:
      - httpd_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  httpd_network:
    driver: overlay
    attachable: true
